sudo: required
services:
  - docker
language: bash
before_install:
  - docker pull lpenz/omnilint
  - ls -l  ~/.ssh/
  - cat ~/.ssh/known_hosts
  - echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
  - cat ~/.ssh/known_hosts
  - ls -l  ~/.ssh/
install:
  - docker build -t ansible-playbooks:latest .
  - docker ps -a
script:
  - docker run -it --rm -v $PWD:/home/user/work -e MY_UID=$UID ansible-playbooks
  - docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
