language: python
addons:
  apt:
    packages:
      - cabal-install
      - haskell-platform
      - ansible # https://github.com/travis-ci/apt-package-whitelist/issues/495
sudo: required
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ansible cabal-install haskell-platform
  - cabal update
  - cabal install --force-reinstalls shellcheck
  - pip install flake8 py3kwarn
script:
  - ansible-playbook -i localhost, -c local playbook-lpenz-nox.yml
  - nosetests --with-doctest
  - grep -l '#!/bin/sh'   roles/*/files/scripts/* | xargs ~/.cabal/bin/shellcheck
  - grep -l '#!/bin/bash' roles/*/files/scripts/* | xargs ~/.cabal/bin/shellcheck
  - grep -l '#!/usr/bin/python' roles/*/files/scripts/* | xargs flake8
  - grep -l '#!/usr/bin/python' roles/*/files/scripts/* | xargs py3kwarn
  - nosetests --with-doc --exe
