sudo: required
services:
  - docker
language: bash
install:
  - docker build -t ansible-playbooks:latest .
  - docker ps -a
script:
  - docker run -it --rm -v $PWD:/home/user/work -e MY_UID=$UID ansible-playbooks
