sudo: required
services:
  - docker
language: bash
before_install:
  - docker pull lpenz/omnilint
install:
  - docker build -t ansible-playbooks:latest .
  - docker ps -a
script:
  - docker run -it --rm -v $PWD:/home/user/work -e MY_UID=$UID ansible-playbooks
  - docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" omnilint
