language: generic
jobs:
  include:
    - name: omnilint
      install: docker pull lpenz/omnilint:v0.2
      script: docker run --rm -u "$UID" -v "$PWD:$PWD" -w "$PWD" lpenz/omnilint
    - name: ansible-playbook
      install: docker build -t ansible-playbooks:latest .
      script: docker run --rm -u "$UID" -w "$PWD" -v "$HOME:$HOME" -v /etc/passwd:/etc/passwd ansible-playbooks
    - name: ansible-playbook --check
      install: docker build -t ansible-playbooks:latest .
      script: docker run --rm -u "$UID" -w "$PWD" -v "$HOME:$HOME" -v /etc/passwd:/etc/passwd ansible-playbooks ansible-playbook playbook-all.yml --check
