#!/bin/bash

set -e -x

grep -l '#!/bin/sh' roles/*/files/scripts/* | xargs shellcheck
grep -l '#!/bin/bash' roles/*/files/scripts/* | xargs shellcheck
grep -l '#!/usr/bin/env python3' roles/*/files/scripts/* | xargs flake8
# sudo ansible-playbook -u "$USER" -i localhost, -c local playbook-sudo-term.yml
ansible localhost -m ansible.builtin.setup
ansible-playbook -u "$USER" -i localhost, -c local playbook-user-term.yml
