#!/bin/bash

set -e -x

grep -l '#!/bin/sh'   roles/*/files/scripts/* | xargs shellcheck
grep -l '#!/bin/bash' roles/*/files/scripts/* | xargs shellcheck
grep -l '#!/usr/bin/python' roles/*/files/scripts/* | xargs flake8
nosetests3 --with-doc --exe
# sudo ansible-playbook -i localhost, -c local playbook-sudo-term.yml # unable to test this on travis for now
ansible-playbook -i localhost, -c local playbook-user-term.yml

