---

- name: create home dirs
  file:
    state: directory
    dest: "{{ lookup('env','HOME') }}/{{ item }}"
    mode: 0755
  with_items:
    - .config
    - .config/fontconfig
    - .local
    - .local/share
    - .local/share/fonts

- name: install dotfiles
  copy:
    src: "dotfiles/{{ item.src }}"
    dest: "{{ lookup('env','HOME') }}/{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: "Xresources"   , dest: ".Xresources"    }
    - { src: "xsession"     , dest: ".xsession"      }

- name: some dot files must exist
  copy:
    content: ''
    dest: "{{ lookup('env','HOME') }}/{{ item }}"
    force: no
    mode: 0644
  with_items:
     - .Xresources.local
     - .stalonetrayrc

- name: install fonts.conf that gets nix fonts
  template:
    src: fonts.conf.j2
    dest: "{{ lookup('env','HOME') }}/.config/fontconfig/fonts.conf"
    mode: 0644
  notify: fccache

- name: install inconsolata nerd font for powerline
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v1.2.0/Inconsolata.zip
    dest: ~/.local/share/fonts/
    remote_src: yes
