---
- name: create ~/bin
  file: name="{{lookup('env','HOME')}}/bin" state=directory

- name: install scripts
  copy: src="scripts/{{item}}" dest="~/bin/{{item}}" mode=0755
  with_items:
    - clipinfo.py
    - gkrellmstart
    - myroottail
    - slock
    - tv
    - view-dot
    - warn
    - warnd.py
