---
- name: create ~/bin
  file: name="{{ lookup('env','HOME') }}/bin" state=directory mode=0755

- name: install scripts
  copy:
    src: "scripts/{{ item }}"
    dest: "{{ lookup('env','HOME') }}/bin/{{ item }}"
    mode: 0o755
  with_items:
    - clipinfo.py
    - image-to-clipboard
    - myroottail
    - pactl-volume
    - steam-session
    - tv
    - view-dot
    - view-plantuml
    - warn
    - warnd.py

