---

- name: create ~/.config/systemd/user
  file: name="{{ lookup('env','HOME') }}/{{ item }}" state=directory
  with_items:
    - .config/systemd
    - .config/systemd/user

- name: install systemd user graphical services
  copy:
    src: "systemd/{{ item }}"
    dest: "{{ lookup('env','HOME') }}/.config/systemd/user/{{ ansible_user }}-x-{{ item }}"
    mode: 0644
  with_items:
    - clipinfo-clipboard.service
    - clipinfo-primary.service
    - gkrellm.service
    - myroottail.service
    - nmapplet.service
    - pasystray.service
    - stalonetray.service
    - warnd.service
    - wm.service
    - xscreensaver.service
    - xscreensaver-watch.service
  notify: systemd-reload
