---
- name: configure ansible_userspace_bits == "64" if adequate
  set_fact: debian_arch="amd64"
  when: ansible_userspace_bits == "64"
- name: configure ansible_userspace_bits == "32" if adequate
  set_fact: debian_arch="i386"
  when: ansible_userspace_bits == "32"

- name: apt install packages required by dropbox or by my usage
  apt:
    state: present
    package:
      - cryptmount # to mount dropboxcrypted

- name: package_facts
  package_facts:

- name: download dropbox
  apt:
    state: present
    deb: "https://www.dropbox.com/download?dl=packages/debian/dropbox_1.6.2_{{ debian_arch }}.deb"
  when: not "dropbox" in ansible_facts.packages

- name: configure sysctl inotify max
  sysctl: name="fs.inotify.max_user_watches" value=100000 sysctl_set=yes

- name: check if ufw installed
  stat: path=/usr/sbin/ufw
  register: stat_ufw
- name: add ufw rule for dropbox
  copy: src=ufw-dropbox.conf dest=/etc/ufw/applications.d/lpenz-dropbox owner=root group=root mode=0644
  when: stat_ufw.stat.exists
- name: configure ufw
  ufw: rule=allow name=dropbox
  when: stat_ufw.stat.exists

- name: cmtab
  blockinfile:
    path: /etc/cryptmount/cmtab
    owner: root
    group: root
    mode: 0644
    marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ item.label }}"
    block: |
      {{ item.label }} {
        dev=$(HOME)/{{ item.file }}
        dir=$(HOME)/{{ item.dir }}
        fstype=auto
        keyformat=luks
      }
  with_items:
    - { label: "dropboxcrypted", file: "Dropbox/private/crypted.vol", dir: "dropboxcrypted" }
