---
- name: "apt | create /etc/apt/keyrings"
  file: dest=/etc/apt/keyrings state=directory mode=0755

- name: "apt | download google signing key"
  get_url:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/keyrings/google_signing_key.pub

- name: "apt | ensure Google chrome repo present, using a workaround for missing x86 distribution"
  copy:
    content: >
      deb [arch=amd64,signed-by=/etc/apt/keyrings/google_signing_key.pub]
      https://dl.google.com/linux/chrome/deb/ stable main
    dest: "/etc/apt/sources.list.d/google-chrome.list"
    mode: 0o644
  notify: apt-update

- name: run apt-update if necessary
  meta: flush_handlers

- name: "apt | ensure Google chrome present"
  apt: name=google-chrome-stable update_cache=yes
