---
- name: install base X packages
  apt:
    state: present
    package:
      - copyq
      - dbus-x11 # dep
      - dunst
      - fonts-dejavu
      - fonts-inconsolata
      - fonts-recommended
      - git-gui
      - gitk
      - gkrellm
      - gkrellshoot
      - gkrelltop
      - libnotify-bin
      - pasystray
      - root-tail
      - rxvt-unicode
      - stalonetray
      - suckless-tools
      - vim-gtk3
      - xfonts-terminus
      - xscreensaver
      - xserver-xorg
      # Audio:
      - gkrellm-volume
      - pavucontrol
      - pavumeter
      - pulseaudio
      - pulseaudio-utils

- name: install notion
  apt: state=present package=notion
  when: ansible_lsb.id != "Raspbian"

- name: setup rxvt-unicode as x-terminal-emulator
  alternatives: name=x-terminal-emulator path=/usr/bin/rxvt-unicode
