---
- apt: package={{item}} state=present
  with_items:
    - vim-gtk3
    - rxvt-unicode-256color
    - notion
    - gitk
    - git-gui
    - xserver-xorg
    - stalonetray
    - root-tail
    - suckless-tools
    - libnotify-bin
    - mate-notification-daemon
    - xfonts-jmk
    - xfonts-terminus
    - xfonts-terminus-dos
    - dbus-x11 # dep of xselctrl and others
    - gkrellm
    - gkrellshoot
    - gkrelltop
    - gkrellweather
    - gpaste-applet

- name: setup rxvt-unicode-256-colors alternative
  alternatives: name=x-terminal-emulator path=/usr/bin/rxvt-unicode
