---
- apt: package={{item}} state=present
  with_items:
    - dbus-x11 # dep
    - git-gui
    - gitk
    - gkrellm
    - gkrellshoot
    - gkrelltop
    - libnotify-bin
    - mate-notification-daemon
    - notion
    - pasystray
    - root-tail
    - rxvt-unicode-256color
    - stalonetray
    - suckless-tools
    - synapse
    - vim-gtk3
    - xfonts-jmk
    - xfonts-terminus
    - xfonts-terminus-dos
    - xserver-xorg

- name: setup rxvt-unicode-256-colors alternative
  alternatives: name=x-terminal-emulator path=/usr/bin/rxvt-unicode
