---
- name: install spotify key
  apt_key:
    keyserver: "hkp://keyserver.ubuntu.com:80"
    id: 0DF731E45CE24F27EEEB1450EFDC8610341D9410

- name: add spotify repository
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"

- name: install spotify-client
  apt:
    name: spotify-client
    update_cache: no
