---
- name: setup pinning
  template:
    src: apt-pinning.j2
    dest: /etc/apt/preferences.d/99pinning
    owner: root
    group: root
    mode: 0o644

- name: debian default apt sources
  apt_repository: repo='deb http://ftp.debian.org/debian {{ item }} main contrib non-free non-free-firmware' state=present
  with_items:
    - stable
    - testing
    - unstable
    - experimental
  notify: apt-update
  when: is_debian

- name: raspbian default apt sources
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - 'deb http://raspbian.raspberrypi.org/raspbian/ bullseye main contrib non-free rpi firmware'
    - 'deb http://archive.raspberrypi.org/debian/ bullseye main ui'
  notify: apt-update
  when: is_raspbian

- name: raspbian repository keys
  apt_key: url='https://ftp-master.debian.org/keys/archive-key-10.asc' id='80D15823B7FD1561F9F7BCDDDC30D7C23CBBABEE' state=present
  notify: apt-update
  when: is_raspbian

- name: rpios default apt sources
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - 'deb http://archive.raspberrypi.org/debian/ bullseye main ui'
    - 'deb http://deb.debian.org/debian bullseye main contrib non-free'
    - 'deb http://deb.debian.org/debian bullseye-updates main contrib non-free'
    - 'deb http://security.debian.org/debian-security bullseye-security main contrib non-free'
  notify: apt-update
  when: is_rpios

- name: rm sources.list
  file: dest=/etc/apt/sources.list state=absent
  notify: apt-update
