---
- name: install packages required by apt_repository
  apt: package=python-apt state=present
  when: ansible_lsb.id == "Debian"

- name: setup pinning
  template:
    src: apt-pinning.j2
    dest: /etc/apt/preferences.d/99pinning
    owner: root
    group: root
    mode: 0644

- name: rm sources.list
  file: dest=/etc/apt/sources.list state=absent
  notify: apt-update

- apt_repository: repo='deb http://ftp.debian.org/debian {{item}} main contrib non-free' state=present
  with_items:
    - stable
    - testing
    - unstable
    - experimental
  notify: apt-update
