---
- name: setup pinning
  template:
    src: apt-pinning.j2
    dest: /etc/apt/preferences.d/99pinning
    owner: root
    group: root
    mode: 0o644

- name: rm sources.list
  file: dest=/etc/apt/sources.list state=absent
  notify: apt-update

- name: debian default apt sources
  deb822_repository:
    name: debian
    uris: http://ftp.debian.org/debian
    suites: [stable, testing, unstable, experimental]
    components: [main, contrib, non-free, non-free-firmware]
  notify: apt-update
  when: is_debian

- name: create /etc/apt/keyrings
  file: dest=/etc/apt/keyrings state=directory mode=0755
  when: is_raspbian

- name: download archive-key-10.gpg
  shell:
    cmd: >
      set -o pipefail;
      curl -L https://ftp-master.debian.org/keys/archive-key-10.asc |
      gpg --dearmor > /etc/apt/keyrings/archive-key-10.gpg
    executable: /bin/bash
    creates: /etc/apt/keyrings/archive-key-10.gpg
  when: is_raspbian

- name: raspbian default apt sources
  deb822_repository:
    name: '{{ item.name }}'
    uris: '{{ item.uri }}'
    suites: ['{{ item.suite }}']
    components: '{{ item.components }}'
    signed_by: /etc/apt/keyrings/archive-key-10.gpg
  loop:
    - name: raspbian
      uri: http://raspbian.raspberrypi.org/raspbian/
      suite: trixie
      components: [main, contrib, non-free, rpi, firmware]
    - name: raspberrypi
      uri: http://archive.raspberrypi.org/debian/
      suite: trixie
      components: [main]
  notify: apt-update
  when: is_raspbian

- name: rpios default apt sources
  deb822_repository:
    name: '{{ item.name }}'
    uris: '{{ item.uri }}'
    suites: '{{ item.suites }}'
    components: '{{ item.components }}'
  loop:
    - name: rpios-raspberrypi
      uri: http://archive.raspberrypi.org/debian/
      suites: [trixie]
      components: [main]
    - name: rpios-debian
      uri: http://deb.debian.org/debian
      suites: [trixie, trixie-updates]
      components: [main, contrib, non-free, non-free-firmware]
    - name: rpios-security
      uri: http://security.debian.org/debian-security
      suites: [trixie-security]
      components: [main, contrib, non-free]
  notify: apt-update
  when: is_rpios
