---
- name: raspbian, setup pinning
  template:
    src: apt-pinning-raspbian.j2
    dest: /etc/apt/preferences.d/99pinning
    owner: root
    group: root
    mode: 0o644

- name: raspbian, install Debian keys
  apt_key: url='https://ftp-master.debian.org/keys/archive-key-10.asc' id='80D15823B7FD1561F9F7BCDDDC30D7C23CBBABEE' state=present
  notify: apt-update

- name: raspbian default apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - 'deb http://raspbian.raspberrypi.org/raspbian/ bullseye main contrib non-free rpi firmware'
    - 'deb http://archive.raspberrypi.org/debian/ bullseye main ui'
  notify: apt-update

- name: raspbian, rm sources.list
  file: dest=/etc/apt/sources.list state=absent
  notify: apt-update
