---
- include: aptcfg.yml
- include: packagecloud.yml

- name: run apt-update if necessary
  meta: flush_handlers

- include: packages.yml

- name: install wifi-disable-when-wired
  copy: src=99-disable-wireless-when-wired dest=/etc/NetworkManager/dispatcher.d/99-disable-wireless-when-wired owner=root group=root mode=0755

