---
- import_tasks: aptcfg.yml

- import_tasks: packagecloud.yml

- name: run apt-update if necessary
  meta: flush_handlers

- import_tasks: packages.yml

- name: setup default locale
  lineinfile:
    path: /etc/default/locale
    line: LANG=en_US.UTF-8
    regex: ^LANG *=

- name: setup generated locales
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - "en_US" # ISO-8859-1
    - "en_US.UTF-8"
    - "pt_BR" # ISO-8859-1
    - "pt_BR.UTF-8"

- name: set up mail alias for root
  lineinfile:
    path: /etc/aliases
    line: "root: lpenz@lpenz.org"

- name: install wifi-disable-when-wired
  copy: src=99-disable-wireless-when-wired dest=/etc/NetworkManager/dispatcher.d/99-disable-wireless-when-wired owner=root group=root mode=0755

- name: install sysctl.d/local-userns.conf
  copy:
    src: sysctl.d/local-userns.conf
    dest: /etc/sysctl.d/local-userns.conf
    owner: root
    group: root
    mode: 0o644

- name: ufw needs iptables-legacy alternative
  alternatives: name=iptables path=/usr/sbin/iptables-legacy

- import_tasks: ssh-server-config.yml
- import_tasks: rkhunter.yml
- import_tasks: sudo.yml
- import_tasks: modprobe.yml
- import_tasks: syncthing.yml
- import_tasks: rsyslog.yml

- import_tasks: network-rpi.yml
  when: is_rpi
