---
- name: raspbian, setup country for wpa_supplicant
  lineinfile:
    path: /etc/wpa_supplicant/wpa_supplicant.conf
    line: country=IE
    regexp: country=

- name: raspbian, disable wpa_supplicant in systemd
  systemd:
    name: wpa_supplicant.service
    enabled: no

- name: raspbian, install network-manager and resolvconf
  apt:
    state: present
    name:
      - network-manager
      - resolvconf

- name: raspbian, remove unneeded packages
  apt:
    state: absent
    name:
      - openresolv
      - dhcpcd5
