---
- name: rpi, setup wifi country
  copy:
    src: "modprobe.d/cfg80211_regdomain.conf"
    dest: "/etc/modprobe.d/cfg80211_regdomain.conf"
    owner: root
    group: root
    mode: 0o644

- name: rpi, disable wpa_supplicant in systemd
  systemd:
    name: wpa_supplicant.service
    enabled: no

- name: rpi, enable network-manager in systemd
  systemd:
    name: NetworkManager.service
    enabled: yes

- name: rpi, start network-manager in systemd
  systemd:
    name: NetworkManager.service
    state: started
  when: not ansible_is_chroot

- name: rpi, remove unneeded packages
  apt:
    state: absent
    name:
      - openresolv
      - dhcpcd5

- name: rpi, check if wifi is blocked
  command: rfkill list
  register: wifi
  changed_when: false

- name: rpi, unblock wifi
  command: rfkill unblock 0
  when: '"Soft blocked: yes" in wifi.stdout'
  changed_when: '"Soft blocked: yes" in wifi.stdout'
