---
- name: rpi, setup crda country
  lineinfile:
    path: /etc/default/crda
    line: REGDOMAIN=IE
    regexp: REGDOMAIN=

- name: rpi, setup country for wpa_supplicant
  lineinfile:
    path: /etc/wpa_supplicant/wpa_supplicant.conf
    line: country=IE
    regexp: country=

- name: rpi, disable wpa_supplicant in systemd
  systemd:
    name: wpa_supplicant.service
    enabled: no

- name: rpi, enable network-manager in systemd
  systemd:
    name: NetworkManager.service
    enabled: yes

- name: rpi, remove unneeded packages
  apt:
    state: absent
    name:
      - openresolv
      - dhcpcd5

- name: rpi, check if wifi is blocked
  command: rfkill list
  register: wifi
  changed_when: false

- name: rpi, unblock wifi
  command: rfkill unblock 0
  when: '"Soft blocked: yes" in wifi.stdout'
  changed_when: '"Soft blocked: yes" in wifi.stdout'
