---
- apt:
    state: present
    package:
      - ansible
      - apt-transport-https
      - emacs
      - gawk # required by tmux-fingers
      - git
      - htop
      - keychain
      - mc
      - neovim
      - network-manager
      - tmux
      - vim
      - zsh
