---
- apt:
    state: present
    package:
      - ansible
      - debian-archive-keyring
      - emacs
      - fzf
      - gawk # required by tmux-fingers
      - git
      - htop
      - keychain
      - locales
      - mc
      - neovim
      - network-manager
      - renameutils
      - ripgrep
      - rkhunter
      - tmux
      - vim
      - zsh
