---
- apt_key: url='https://packagecloud.io/lpenz/lpenz/gpgkey' id='418A7F2FB0E1E6E7EABF6FE8C2E73424D59097AB' state=present

- apt_repository: repo='deb https://packagecloud.io/lpenz/lpenz/debian/ stretch main' update_cache=no
  register: aptup3

- apt: update_cache=yes
  when: aptup3.changed

