---
- name: install base packages
  apt:
    state: present
    package:
      - ansible
      - aptitude
      - cryptmount
      - gawk # required by tmux-fingers
      - git
      - keychain
      - locales
      - mc
      - neovim
      - network-manager
      - openssh-server
      - pmount
      - renameutils
      - syncthing
      - tmux
      - ufw
      - vim
