---
- name: install base packages
  apt:
    state: present
    package:
      - ansible
      - cryptmount
      - direnv
      - emacs
      - fd-find
      - fzf
      - gawk # required by tmux-fingers
      - git
      - htop
      - keychain
      - locales
      - mc
      - neovim
      - network-manager
      - openssh-server
      - pmount
      - renameutils
      - ripgrep
      - rkhunter
      - syncthing
      - tmux
      - ufw
      - vim
      - zsh
