---
- name: packagecloud-key-remove-old
  apt_key: id='D59097AB' state=absent

- name: packagecloud-key-import-new
  apt_key: url='https://packagecloud.io/lpenz/lpenz/gpgkey' id='3436F2D037B9886CDCA0318C06D53CED378B88C5' state=present

- apt_repository: repo='deb https://packagecloud.io/lpenz/lpenz/debian/ stretch main' update_cache=no
  notify: apt-update
