---
- apt: package={{item}} state=present
  with_items:
    - vim
    - zsh
    - ansible
    - keychain
    - tmux
    - git
    - apt-transport-https
    - htop
    - mc
    - at-spi2-core # avoid spacemacs warning
