---

- name: set /etc/rsyslog.conf
  copy:
    dest: /etc/rsyslog.conf
    src: rsyslog/rsyslog.conf
    owner: root
    group: root
    mode: 0o644
  notify: rsyslog-restart

- name: add term rsyslog conf to /etc/rsyslog.d
  copy:
    dest: /etc/rsyslog.d/99-lpenz-default.conf
    src: rsyslog/rsyslog-lpenz-default.conf
    owner: root
    group: root
    mode: 0o644
  notify: rsyslog-restart
