---
- name: check if ufw installed
  stat: path=/usr/sbin/ufw
  register: stat_ufw
- name: ufw allow syncthing
  ufw: rule=allow name=syncthing
  when: stat_ufw.stat.exists

- name: cmtab
  blockinfile:
    path: /etc/cryptmount/cmtab
    owner: root
    group: root
    mode: 0o644
    marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ item.label }}"
    block: |
      {{ item.label }} {
        dev=$(HOME)/{{ item.file }}
        dir=$(HOME)/{{ item.dir }}
        fstype=auto
        keyformat=luks
      }
  with_items:
    - { label: "syncrypted", file: "Sync/crypted.vol", dir: "syncrypted" }
