# lpenz .zshenv

export LC_ALL=en_US.UTF-8
export LANGUAGE=en
export PYTHONIOENCODING=UTF-8

export CVSIGNORE=".*.swp .*.swo .swp .swo cscope.out *.o.flags .depend"
export CVS_RSH="ssh"
export GTK2_RC_FILES=$HOME/.gtkrc-2.0
export LUA_HISTORY=$HOME/.lua_history
export PYTHONSTARTUP=~/.pystartup
export XAUTHORITY=~/.Xauthority
export RUST_SRC_PATH=/usr/src/rust/src

if [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
    . $HOME/.nix-profile/etc/profile.d/nix.sh
    export LOCALE_ARCHIVE_2_27=$HOME/.nix-profile/lib/locale/locale-archive
    export NIX_IGNORE_SYMLINK_STORE=1
fi

GUIX_PROFILE="$HOME/.guix-profile"
export GUIX_LOCPATH="$GUIX_PROFILE/lib/locale"
# Not putting guix in path:
# if [ -e "$GUIX_PROFILE/etc/profile" ]; then
#      . "$GUIX_PROFILE/etc/profile"
# fi

typeset -U path
path=(~/.cargo/bin "$path[@]")
path=(~/.local/bin "$path[@]")
path=(~/bin "$path[@]")

# Local customizations
if test -r ~/.zshenv.local; then . ~/.zshenv.local; fi
