# lpenz .zshenv

typeset -U path
path=(~/.cargo/bin "$path[@]")
path=(~/.local/bin "$path[@]")
path=(~/bin "$path[@]")
export CVSIGNORE=".*.swp .*.swo .swp .swo cscope.out *.o.flags .depend"
export CVS_RSH="ssh"
export GTK2_RC_FILES=$HOME/.gtkrc-2.0
export LUA_HISTORY=$HOME/.lua_history
export MANPATH=:$HOME/.man
export LC_ALL=en_US.UTF-8
export LANGUAGE=en
export VISUAL=/usr/bin/vim
export EDITOR=$VISUAL
export PYTHONSTARTUP=~/.pystartup
export XAUTHORITY=~/.Xauthority

# Local customizations
if test -r ~/.zshenv.local; then . ~/.zshenv.local; fi
