---
- set_fact: debian_arch="amd64"
  when: ansible_userspace_bits == "64"
- set_fact: debian_arch="i386"
  when: ansible_userspace_bits == "32"

- get_url: dest=/var/cache/apt/archives url="https://www.dropbox.com/download?dl=packages/debian/dropbox_2015.10.28_{{debian_arch}}.deb"

- apt: package={{item}} state=present
  with_items:
    - python-gpgme # required by dropbox
    - dropbox

- copy: dest=/etc/sysctl.d/local-dropbox.conf src=sysctl-local-dropbox.conf owner=root group=root mode=0644

- copy: src=ufw-dropbox.conf dest=/etc/ufw/applications.d/lpenz-dropbox owner=root group=root mode=0644
- ufw: rule=allow from_ip="{{localnet}}" name=dropbox

