---
- name: apt-update
  apt: update_cache=yes

- name: ssh-server-restart
  service: name=sshd state=restarted
  when: not ansible_is_chroot

- name: rsyslog-restart
  service: name=rsyslog state=restarted
  when: not ansible_is_chroot

- name: systemd-reload
  systemd: daemon_reload=yes
