#!/bin/bash

export PATH=~/bin:~/.cargo/bin:~/.local/bin:~/.nix-profile/bin:$PATH
export LANGUAGE=en

if [ -z "$LC_ALL" ]; then
	export LC_ALL=en_US.UTF-8
fi

xset b off
xsetroot -solid black
setxkbmap -option compose:ralt

if [ -f "$HOME/.xsession.local" ]; then
    # shellcheck source=/dev/null
    . "$HOME/.xsession.local"
fi

nice -n 19 ~/bin/warnd.py -f ~/.warnd_fifo -l "$HOME/.warnd_log1,$HOME/.warnd_log2" > /dev/null &

nice -n 19 ~/bin/clipinfo.py -m 79 -c -b -o ~/.selection_clipboard.txt &
nice -n 19 ~/bin/clipinfo.py -m 79 -p -b -o ~/.selection_primary.txt &
# nice -n 19 ~/bin/clipinfo.py -m 79 -s -b -o ~/.selection_secondary.txt &

(sleep 10; exec ~/bin/myroottail) &

gkrellm &
(sleep 15; exec stalonetray --window-type dock --geometry 3x5) &
(sleep 30; exec nm-applet) &
(sleep 30; exec pasystray) &

xscreensaver &
logger -t xscreensaver STARTED
(sleep 15; set -e -o pipefail; xscreensaver-command -watch | logger -t xscreensaver) &

if [ -z "$XSESSION_SKIP_DROPBOX" ]; then
    (sleep 30; dropbox start) &
fi

if [ -z "$XSESSION_SKIP_PIDGIN" ]; then
    (sleep 30; exec pidgin) &
fi

if [ -z "$XSESSION_SKIP_NOTION" ]; then
    exec /usr/bin/notion 
fi
