#!/bin/bash

export PATH=~/bin:$PATH
export LANGUAGE=en

if [ -z "$LC_ALL" ]; then
	export LC_ALL=en_US.UTF-8
fi

xset b off
xsetroot -solid black

nice -n 19 ~/bin/warnd.py -f ~/.warnd_fifo -l "$HOME/.warnd_log1,$HOME/.warnd_log2" > /dev/null &

nice -n 19 ~/bin/clipinfo.py -m 79 -c -b -o ~/.clipinfo.txt &
nice -n 19 ~/bin/clipinfo.py -m 79 -s -b -o ~/.clipinfo2.txt &

nice -n 19 ~/bin/xselctrl.py &

(sleep 30; ~/bin/myroottail) &

~/bin/gkrellmstart
(sleep 30; dropbox start) &

if [ -z "$XSESSION_SKIP_NOTION" ]; then
    exec /usr/bin/notion 
fi
