#!/bin/bash

set -e -x

cryptmount -u "syncrypted"
md5sum "syncrypted"
cp -v "$HOME/Sync/crypted.vol" "$HOME/Sync/crypted-$(timestamp)-$(hostname -s).vol"
s3cmd put "$HOME/Sync/crypted.vol" s3://lpenz-backup-ire/
