#!/bin/bash

set -x -e

: gc conteiners
docker ps --filter 'status=exited'  -q | xargs -r docker rm
docker ps --filter 'status=created' -q | xargs -r docker rm

: gc images
docker images --filter "dangling=true" -q | xargs -r docker rmi

