#!/bin/bash

NAME="${USER}/${PWD##*/}"
NAME="${NAME,,}"

if grep -q '^\(COPY\|ADD\) ' Dockerfile; then

    set -x -e
    docker build -t "$NAME" . "$@"

else
    TMPDIR=$(mktemp -d)
    trap 'rm -rf "$TMPDIR"' EXIT
    BUILD_DIR="$TMPDIR/$NAME"

    set -x -e

    mkdir -p "$BUILD_DIR"
    cp Dockerfile "$BUILD_DIR/"
    cd "$BUILD_DIR/"
    docker build -t "$NAME" . "$@"
fi

