#!/bin/bash

TMP=$(mktemp)
trap 'rm -f $TMP' EXIT

cat <<END >"$TMP"
#!/bin/bash

RG=0

for d in "\$@"; do
    printf 'dodirs[1]: Entering directory %s%s%s\\n' "\\\`" "$PWD/\$d" "'"
    cd "\$d" || continue
    echo + "$@"
    $@
    R=\$?
    if [ "\$R" != 0 ]; then
        RG="\$R"
    fi
    printf 'dodirs[1]: Leaving directory %s%s%s\\n' "\\\`" "$PWD/\$d" "'"
    cd "$PWD" || :
done

exit "\$RG"

END

set -e -x

find . -mindepth 1 -maxdepth 1 -type d -exec /bin/bash "$TMP" {} +
