#!/bin/bash

date="${1-$(date)}"
orig="${2-origin/main}"

export FILTER_BRANCH_SQUELCH_WARNING=1

set -e -x

git filter-branch --env-filter "export GIT_AUTHOR_DATE=\"${date}\"; export GIT_COMMITTER_DATE=\"\$GIT_AUTHOR_DATE\"" "${orig}..HEAD"
git update-ref -d refs/original/refs/heads/devel || :
git update-ref -d refs/original/refs/heads/main || :
git-sign
