#!/bin/bash

git update-index --refresh
if ! git diff-index --quiet HEAD --; then
	echo Stash or commit all changes before using this script >&2
	exit 1
fi

TMP=$(mktemp)
trap 'rm -f $TMP' EXIT

set -e -x

git log -1 --format=%B >"$TMP"
git reset HEAD^
git add .
git ls-files --deleted | xargs -r git rm
git commit -F "$TMP"
