#!/bin/bash

set -e

GLOBAL=$(which global)
DIR=$(realpath "$GLOBAL")

if ! echo "$DIR" | grep -q nix/store; then
    exec gtags "$@"
fi

DIR=$(dirname "$DIR")
DIR=$(dirname "$DIR")
CONF="$DIR/share/gtags/gtags.conf"

if [ -e "$CONF" ]; then
  exec gtags "--gtagsconf=$CONF" --gtagslabel=pygments "$@"
fi

exec gtags "$@"
