#!/bin/bash

if [ -e ./.envrc ]; then
    # shellcheck disable=SC1091
    source ./.envrc
fi

done=0

set -e -x

if [ -e build.sh ]; then
    exec ./build.sh
fi

if [ -e SConstruct ]; then
    scons --max-drift=1 --implicit-cache "$@"
    done=$((done + 1))
fi

if [ -e Cargo.toml ]; then
    cargo clippy
    cargo test "$@"
    done=$((done + 1))
fi

if [ -e CMakeLists.txt ]; then
    cmake "$@"
    done=$((done + 1))
fi

if [ -e Makefile ]; then
    make -k "$@"
    done=$((done + 1))
fi

if [ -e pyproject.toml ]; then
    mypy
    flake8 .
    pytest
    done=$((done + 1))
fi

if [ "$done" -eq "0" ] && [ -e Dockerfile ]; then
    docker-build
fi
