#!/bin/bash

labeldir=/dev/disk/by-label

set -e

if ! [ -d "$labeldir" ]; then
    echo "$labeldir not found" >&2
    exit 1
fi

cd "$labeldir"

if [ "$#" = 0 ]; then
    echo "Available labels:"
    ls -1
    exit 0
fi

label="$1"

set -e -x

pmount "$label"
: mounted at "/media/${label}"
