#!/bin/bash

NAME=${1?name not found}
shift

mkdir -p "$HOME/logs/$NAME"

TMP=$(mktemp)
trap 'rm -f $TMP' EXIT
chmod u+x "$TMP"

cat > "$TMP" <<EOF
echo \$i
date
set -x
time (
$@
)
RV=\$?
: result \$RV
exit \$RV
EOF

set -o pipefail
i=0
RV=0
while ! read -r -t 1; do
    i=$((i+1))
    FILE="$HOME/logs/$NAME/$(date +%s).txt"
    echo "$FILE"
    "$TMP" 2>&1 | tee "$FILE"
    RV=$?
done
exit "$RV"
