#!/bin/bash

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

PIPE=""
PREFIX=""

while getopts "t:p:" opt; do
  case ${opt} in
    t) PIPE="$OPTARG";;
    p) PREFIX="$OPTARG";;
    ?)
      echo "Invalid option" >&2
      exit 1
      ;;
  esac
done

shift $((OPTIND - 1))

if [ -z "$PREFIX" ]; then
    LOGDIR=${LOGDIR:-$HOME/logs}
    LOGDIR=${LOGDIR%%/}
    PREFIX="$LOGDIR/$(date +%s)"
fi

LOGDIR="${PREFIX%/}"
mkdir -p "$LOGDIR"

L="${PREFIX}-run.txt"

printf "%s start with log %s\n" "$(date +%FT%T)" "$L"

{
    printf "%s start [%s]\n" "$(date +%FT%T)" "$*"
    echo + "$@"
    set +e
    /usr/bin/time -o "$TMP" "$@"
    ret=$?
    set -e
    printf "%s end   [%s]\n" "$(date +%FT%T)" "$*"
    cat "$TMP"
    echo "\$?" = "$ret"
} >"$L" 2>&1

if [ "$ret" = "0" ]; then
    LEND="${PREFIX}-pass.txt"
else
    LEND="${PREFIX}-fail.txt"
fi

if [ -n "$PIPE" ]; then
    "${PIPE[@]}" <"$L" >"$LEND"
    rm -f "$L"
else
    mv "$L" "$LEND"
fi

printf "%s end   with log %s\n" "$(date +%FT%T)" "$LEND"

exit "$ret"
