#!/bin/bash

set -e -o pipefail

TMP=$(mktemp)
trap 'rm -f $TMP' EXIT

set -x
wget https://sh.rustup.rs -O "$TMP"
bash "$TMP" --no-modify-path --default-toolchain nightly -y
# cargo install clippy cargo-update
cargo install cargo-update
rustup component add clippy-preview
rustup component add rustfmt-preview

