#!/bin/bash

set -e -o pipefail

TMP=$(mktemp)
trap 'rm -f $TMP' EXIT

set -x
wget https://sh.rustup.rs -O "$TMP"
# bash "$TMP" --no-modify-path --default-toolchain nightly -y
bash "$TMP" --no-modify-path -y
cargo install cargo-update cargo-edit
rustup component add clippy
rustup component add rustfmt

