#!/bin/bash

# from the first comment at https://cafbit.com/post/terminal_window_size_detection_over/

set -e

printf '\e[18t' # returns \e[8;??;??t
IFS='['
read -r -d t -s _ params
IFS=';' read -r -a array <<< "$params"
set -- "${array[@]}"
[ $# = 3 ] && [ "$1" = 8 ] && shift
[ $# != 2 ] && echo error >&2 && exit 1

set -x
stty rows "$1" cols "$2"

