#!/bin/bash

# Generates numeric-only timestamps.
# Other useful formats natively supported by date:
# - date "+%FT%T" = 2006-01-02T15:04:05"
# - date -Is      = 2006-01-02T15:04:05+00:00 (tz)

set -e -o pipefail

date "+%Y%m%d%H%M%S"
