---

- name: create home dirs
  file:
    state: directory
    dest: "{{ lookup('env','HOME') }}/{{ item }}"
    mode: 0755
  with_items:
    - .config
    - .mc
    - nix

- name: install dotfiles
  copy:
    src: "dotfiles/{{ item.src }}"
    dest: "{{ lookup('env','HOME') }}/{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: "agignore"      , dest: ".agignore"             }
    - { src: "clang-format"  , dest: ".clang-format"         }
    - { src: "expectk.rc"    , dest: ".expectk.rc"           }
    - { src: "expect.rc"     , dest: ".expect.rc"            }
    - { src: "mailcap"       , dest: ".mailcap"              }
    - { src: "mc.ini"        , dest: ".mc/ini"               }
    - { src: "mime.types"    , dest: ".mime.types"           }
    - { src: "nix.conf"      , dest: ".config/nix/"          }
    - { src: "pdbrc"         , dest: ".pdbrc"                }
    - { src: "pdb_rc.py"     , dest: ".pdb_rc.py"            }
    - { src: "pystartup"     , dest: ".pystartup"            }
    - { src: "screenrc"      , dest: ".screenrc"             }
    - { src: "topgrade.toml" , dest: ".config/topgrade.toml" }

- name: gdbinit save history
  lineinfile:
    dest: "~/.gdbinit"
    create: yes
    state: present
    mode: 0600
    line: set history save on

