---
- name: create ~/.mc
  file: name="{{lookup('env','HOME')}}/.mc" state=directory
- name: install dotfiles
  copy: src="{{item.src}}" dest="{{item.dest}}"
  with_items:
    - { src: "dotfiles/expectk.rc"   , dest: "~/.expectk.rc"   }
    - { src: "dotfiles/expect.rc"    , dest: "~/.expect.rc"    }
    - { src: "dotfiles/mailcap"      , dest: "~/.mailcap"      }
    - { src: "dotfiles/mime.types"   , dest: "~/.mime.types"   }
    - { src: "dotfiles/screenrc"     , dest: "~/.screenrc"     }
    - { src: "dotfiles/mc.ini"       , dest: "~/.mc/ini"       }
    - { src: "dotfiles/pystartup"    , dest: "~/.pystartup"    }
    - { src: "dotfiles/clang-format" , dest: "~/.clang-format" }
    - { src: "dotfiles/pdbrc"        , dest: "~/.pdbrc"        }
    - { src: "dotfiles/pdbrc.py"     , dest: "~/.pdbrc.py"     }
    - { src: "dotfiles/agignore"     , dest: "~/.agignore"     }

- name: gdbinit save history
  lineinfile:
    dest: "~/.gdbinit"
    create: yes
    state: present
    mode: 0600
    line: set history save on

