---
- name: ~/.config dir must exist
  file: name="{{ lookup('env','HOME') }}/.config" state=directory mode=0755

- name: ~/.config/nix dir must exist
  file: dest="{{ lookup('env','HOME') }}/.config/nix" state=directory mode=0755
- name: ~/.mc dir must exist
  file: name="{{ lookup('env','HOME') }}/.mc" state=directory mode=0755
- name: install dotfiles
  copy: src="{{ item.src }}" dest="{{ item.dest }}" mode=0644
  with_items:
    - { src: "dotfiles/agignore"     , dest: "~/.agignore"     }
    - { src: "dotfiles/clang-format" , dest: "~/.clang-format" }
    - { src: "dotfiles/expectk.rc"   , dest: "~/.expectk.rc"   }
    - { src: "dotfiles/expect.rc"    , dest: "~/.expect.rc"    }
    - { src: "dotfiles/mailcap"      , dest: "~/.mailcap"      }
    - { src: "dotfiles/mc.ini"       , dest: "~/.mc/ini"       }
    - { src: "dotfiles/mime.types"   , dest: "~/.mime.types"   }
    - { src: "dotfiles/nix.conf"     , dest: "~/.config/nix/" }
    - { src: "dotfiles/pdbrc"        , dest: "~/.pdbrc"        }
    - { src: "dotfiles/pdb_rc.py"    , dest: "~/.pdb_rc.py"    }
    - { src: "dotfiles/pystartup"    , dest: "~/.pystartup"    }
    - { src: "dotfiles/screenrc"     , dest: "~/.screenrc"     }

- name: gdbinit save history
  lineinfile:
    dest: "~/.gdbinit"
    create: yes
    state: present
    mode: 0600
    line: set history save on

