---
- name: git config path must exist
  file: name="{{ lookup('env','HOME') }}/.config/git" state=directory mode=0755

- name: git configuration
  git_config:
    scope: global
    name: '{{ item.name }}'
    value: '{{ item.value }}'
  with_items:
    - { name: rerere.enabled, value: 'true' }
    - { name: alias.k, value: 'log --graph --decorate --oneline' }
    - { name: push.default, value: 'matching' }
    - { name: init.defaultBranch, value: 'main' }
    - { name: pull.rebase, value: 'true' }

- name: gitignore setup
  lineinfile: dest=~/.config/git/ignore create=yes mode=0644 line={{ item }}
  with_items:
    - .mypy_cache/
    - /.sconsign.dblite
    - /.find.txt.gz
    - /GPATH
    - /GRTAGS
    - /GTAGS
    - '*.pyc'
    - '*.pyo'
    - '*.~undo-tree~'
