---
- name: git config alias.k
  git_config:
    name: alias.k
    scope: global
    value: log --graph --decorate --oneline

- name: git config rerere
  git_config:
    name: rerere.enabled
    scope: global
    value: true

- name: git config path must exist
  file: name="{{ lookup('env','HOME') }}/.config/git" state=directory mode=0755

- name: gitignore setup
  lineinfile: dest=~/.config/git/ignore create=yes mode=0644 line={{ item }}
  with_items:
    - .mypy_cache/
    - /.sconsign.dblite
    - /.find.txt.gz
    - /GPATH
    - /GRTAGS
    - /GTAGS
    - '*.pyc'
    - '*.pyo'
