---

- name: ~/.gnupg dir must exist
  file: name="{{ lookup('env','HOME') }}/.gnupg" state=directory mode=0700

- name: gpg.conf
  lineinfile:
    path: "{{ lookup('env','HOME') }}/.gnupg/gpg.conf"
    line: '{{ item }}'
    create: true
    mode: 0o600
  loop:
    - keyid-format long
    - with-fingerprint
    - with-sig-list
    - list-options show-notations
