---
- name: syncthing enable
  systemd:
    name: syncthing
    scope: user
    enabled: true
  ignore_errors: true

- name: syncthing start
  systemd:
    name: syncthing
    scope: user
    state: started
  ignore_errors: true
  when: not ansible_is_chroot
