---
- name: syncthing enable
  systemd:
    name: syncthing
    scope: user
    enabled: true
  ignore_errors: true
  when: not ansible_facts["is_chroot"] and ansible_facts["service_mgr"] == "systemd"

- name: syncthing start
  systemd:
    name: syncthing
    scope: user
    state: started
  ignore_errors: true
  when: not ansible_facts["is_chroot"] and ansible_facts["service_mgr"] == "systemd"
