---
- name: create ~/.tmux
  file: name="{{ lookup('env','HOME') }}/.tmux" state=directory mode=0755

- name: create ~/.tmux/plugins
  file: name="{{ lookup('env','HOME') }}/.tmux/plugins" state=directory mode=0755

- name: clone tmux plugin manager
  git:
    repo: "http://github.com/tmux-plugins/tpm"
    dest: "{{ lookup('env','HOME') }}/.tmux/plugins/tpm"
    version: master
  notify: tmux_plugins_install

- name: install my tmux.conf
  copy: src="dotfiles/tmux.conf" dest="~/.tmux.conf" mode=0644
  notify: tmux_plugins_install
