---

- name: create ~/.config/systemd/user
  file: name="{{lookup('env','HOME')}}/{{item}}" state=directory
  with_items:
    - .config
    - .config/systemd
    - .config/systemd/user

- name: install user systemd zcloud.services
  template:
    src: "zcloud.service.j2"
    dest: "{{lookup('env','HOME')}}/.config/systemd/user/{{ansible_user}}-zcloud-{{item}}.service"
    mode: 0644
  with_items: "{{zcloud_providers}}"
  notify: systemd-reload

- name: install private zcloud s3ql mount
  template:
    src: "zcloud-s3ql.service.j2"
    dest: "{{lookup('env','HOME')}}/.config/systemd/user/{{ansible_user}}-zcloud-s3ql-{{ansible_hostname}}.service"
    mode: 0644
  notify: systemd-reload
