---
- name: install zsh dotfiles
  copy: src="dotfiles/{{item}}" dest="~/.{{item}}"
  with_items:
    - zshrc
    - zshenv

- name: create zplugin dir
  file: state=directory dest="{{lookup('env','HOME')}}/.zplugin"

- name: install zplugin
  git:
    repo: "https://github.com/zdharma/zplugin.git"
    dest: "{{lookup('env','HOME')}}/.zplugin/bin"
    update: no

