---
name: CI
on: [ push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://lpenz/omnilint:v0.2
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ansible/ansible-lint-action@master
  ansible-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ansible-check
  check-ansible-debian-sid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: roles-ansible/check-ansible-debian-sid-action@master
        with:
          targets: "./playbook-all.yml"
          group: all

